services:
  app:
    container_name: estore-app
    build: .
    env_file:
      - .env
    environment:
      # .env te Windows er CHROME_PATH ache, eta oitake override kore
      - CHROME_PATH=/usr/bin/chromium
    expose:
      - '8090'
    networks:
      - shared-nginx-net
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '3'

networks:
  shared-nginx-net:
    external: true
    name: amp_portal_backend_app-network